export type EmojiCategoryId =
  | 'recent'
  | 'smileys'
  | 'animals'
  | 'food'
  | 'activities'
  | 'travel'
  | 'objects'
  | 'symbols'

export type EmojiEntry = {
  emoji: string
  slug: string
  keywords?: string
}

export const EMOJI_CATEGORY_LABELS: Record<EmojiCategoryId, string> = {
  recent: 'Recently used',
  smileys: 'Smileys & people',
  animals: 'Animals & nature',
  food: 'Food & drink',
  activities: 'Activities',
  travel: 'Travel & places',
  objects: 'Objects',
  symbols: 'Symbols',
}

/** Curated set with Noto Animated Emoji slugs (fonts.gstatic.com) */
export const EMOJI_CATALOG: Record<Exclude<EmojiCategoryId, 'recent'>, EmojiEntry[]> = {
  smileys: [
    { emoji: '😀', slug: '1f600' },
    { emoji: '😃', slug: '1f603' },
    { emoji: '😄', slug: '1f604' },
    { emoji: '😁', slug: '1f601' },
    { emoji: '😆', slug: '1f606' },
    { emoji: '😅', slug: '1f605' },
    { emoji: '🤣', slug: '1f923' },
    { emoji: '😂', slug: '1f602' },
    { emoji: '🙂', slug: '1f642' },
    { emoji: '😉', slug: '1f609' },
    { emoji: '😊', slug: '1f60a' },
    { emoji: '😇', slug: '1f607' },
    { emoji: '🥰', slug: '1f970' },
    { emoji: '😍', slug: '1f60d' },
    { emoji: '🤩', slug: '1f929' },
    { emoji: '😘', slug: '1f618' },
    { emoji: '😗', slug: '1f617' },
    { emoji: '😚', slug: '1f61a' },
    { emoji: '😋', slug: '1f60b' },
    { emoji: '😛', slug: '1f61b' },
    { emoji: '😜', slug: '1f61c' },
    { emoji: '🤪', slug: '1f92a' },
    { emoji: '🤔', slug: '1f914' },
    { emoji: '🤐', slug: '1f910' },
    { emoji: '🤨', slug: '1f928' },
    { emoji: '😐', slug: '1f610' },
    { emoji: '😑', slug: '1f611' },
    { emoji: '😶', slug: '1f636' },
    { emoji: '😏', slug: '1f60f' },
    { emoji: '😒', slug: '1f612' },
    { emoji: '🙄', slug: '1f644' },
    { emoji: '😬', slug: '1f62c' },
    { emoji: '😴', slug: '1f634' },
    { emoji: '🤤', slug: '1f924' },
    { emoji: '😪', slug: '1f62a' },
    { emoji: '😭', slug: '1f62d' },
    { emoji: '😢', slug: '1f622' },
    { emoji: '😤', slug: '1f624' },
    { emoji: '😠', slug: '1f620' },
    { emoji: '😡', slug: '1f621' },
    { emoji: '🤯', slug: '1f92f' },
    { emoji: '😱', slug: '1f631' },
    { emoji: '🥳', slug: '1f973' },
    { emoji: '🤗', slug: '1f917' },
    { emoji: '🤭', slug: '1f92d' },
    { emoji: '🫶', slug: '1faf6' },
    { emoji: '👍', slug: '1f44d' },
    { emoji: '👎', slug: '1f44e' },
    { emoji: '👏', slug: '1f44f' },
    { emoji: '🙏', slug: '1f64f' },
    { emoji: '🤝', slug: '1f91d' },
    { emoji: '💪', slug: '1f4aa' },
    { emoji: '❤️', slug: '2764_fe0f' },
    { emoji: '🧡', slug: '1f9e1' },
    { emoji: '💛', slug: '1f49b' },
    { emoji: '💚', slug: '1f49a' },
    { emoji: '💙', slug: '1f499' },
    { emoji: '💜', slug: '1f49c' },
    { emoji: '🖤', slug: '1f5a4' },
    { emoji: '💯', slug: '1f4af' },
    { emoji: '✨', slug: '2728' },
    { emoji: '🔥', slug: '1f525' },
  ],
  animals: [
    { emoji: '🐶', slug: '1f436' },
    { emoji: '🐱', slug: '1f431' },
    { emoji: '🐭', slug: '1f42d' },
    { emoji: '🐹', slug: '1f439' },
    { emoji: '🐰', slug: '1f430' },
    { emoji: '🦊', slug: '1f98a' },
    { emoji: '🐻', slug: '1f43b' },
    { emoji: '🐼', slug: '1f43c' },
    { emoji: '🐨', slug: '1f428' },
    { emoji: '🐯', slug: '1f42f' },
    { emoji: '🦁', slug: '1f981' },
    { emoji: '🐮', slug: '1f42e' },
    { emoji: '🐷', slug: '1f437' },
    { emoji: '🐸', slug: '1f438' },
    { emoji: '🐵', slug: '1f435' },
    { emoji: '🦄', slug: '1f984' },
    { emoji: '🐔', slug: '1f414' },
    { emoji: '🐧', slug: '1f427' },
    { emoji: '🐦', slug: '1f426' },
    { emoji: '🦋', slug: '1f98b' },
    { emoji: '🐝', slug: '1f41d' },
    { emoji: '🌸', slug: '1f338' },
    { emoji: '🌺', slug: '1f33a' },
    { emoji: '🌻', slug: '1f33b' },
    { emoji: '🌲', slug: '1f332' },
    { emoji: '🌈', slug: '1f308' },
  ],
  food: [
    { emoji: '🍎', slug: '1f34e' },
    { emoji: '🍊', slug: '1f34a' },
    { emoji: '🍋', slug: '1f34b' },
    { emoji: '🍌', slug: '1f34c' },
    { emoji: '🍉', slug: '1f349' },
    { emoji: '🍇', slug: '1f347' },
    { emoji: '🍓', slug: '1f353' },
    { emoji: '🍕', slug: '1f355' },
    { emoji: '🍔', slug: '1f354' },
    { emoji: '🍟', slug: '1f35f' },
    { emoji: '🌭', slug: '1f32d' },
    { emoji: '🍿', slug: '1f37f' },
    { emoji: '🧁', slug: '1f9c1' },
    { emoji: '🍰', slug: '1f370' },
    { emoji: '🎂', slug: '1f382' },
    { emoji: '🍩', slug: '1f369' },
    { emoji: '☕', slug: '2615' },
    { emoji: '🍵', slug: '1f375' },
    { emoji: '🧃', slug: '1f9c3' },
    { emoji: '🍺', slug: '1f37a' },
    { emoji: '🍻', slug: '1f37b' },
    { emoji: '🥂', slug: '1f942' },
  ],
  activities: [
    { emoji: '⚽', slug: '26bd' },
    { emoji: '🏀', slug: '1f3c0' },
    { emoji: '🏈', slug: '1f3c8' },
    { emoji: '⚾', slug: '26be' },
    { emoji: '🎾', slug: '1f3be' },
    { emoji: '🏐', slug: '1f3d0' },
    { emoji: '🎱', slug: '1f3b1' },
    { emoji: '🎮', slug: '1f3ae' },
    { emoji: '🎯', slug: '1f3af' },
    { emoji: '🎲', slug: '1f3b2' },
    { emoji: '🎸', slug: '1f3b8' },
    { emoji: '🎤', slug: '1f3a4' },
    { emoji: '🎧', slug: '1f3a7' },
    { emoji: '🎬', slug: '1f3ac' },
    { emoji: '🎉', slug: '1f389' },
    { emoji: '🎊', slug: '1f38a' },
    { emoji: '🏆', slug: '1f3c6' },
    { emoji: '🥇', slug: '1f947' },
    { emoji: '🎁', slug: '1f381' },
  ],
  travel: [
    { emoji: '🚗', slug: '1f697' },
    { emoji: '🚕', slug: '1f695' },
    { emoji: '🚌', slug: '1f68c' },
    { emoji: '🚎', slug: '1f68e' },
    { emoji: '🏎️', slug: '1f3ce_fe0f' },
    { emoji: '🚓', slug: '1f693' },
    { emoji: '🚑', slug: '1f691' },
    { emoji: '✈️', slug: '2708_fe0f' },
    { emoji: '🚀', slug: '1f680' },
    { emoji: '🛸', slug: '1f6f8' },
    { emoji: '🚢', slug: '1f6a2' },
    { emoji: '⛵', slug: '26f5' },
    { emoji: '🏠', slug: '1f3e0' },
    { emoji: '🏰', slug: '1f3f0' },
    { emoji: '🗽', slug: '1f5fd' },
    { emoji: '🗼', slug: '1f5fc' },
    { emoji: '🌍', slug: '1f30d' },
    { emoji: '🏖️', slug: '1f3d6_fe0f' },
    { emoji: '⛰️', slug: '26f0_fe0f' },
  ],
  objects: [
    { emoji: '💡', slug: '1f4a1' },
    { emoji: '📱', slug: '1f4f1' },
    { emoji: '💻', slug: '1f4bb' },
    { emoji: '⌚', slug: '231a' },
    { emoji: '📷', slug: '1f4f7' },
    { emoji: '🔋', slug: '1f50b' },
    { emoji: '💰', slug: '1f4b0' },
    { emoji: '💎', slug: '1f48e' },
    { emoji: '🔑', slug: '1f511' },
    { emoji: '🔒', slug: '1f512' },
    { emoji: '📝', slug: '1f4dd' },
    { emoji: '📚', slug: '1f4da' },
    { emoji: '✏️', slug: '270f_fe0f' },
    { emoji: '🎵', slug: '1f3b5' },
    { emoji: '🎶', slug: '1f3b6' },
  ],
  symbols: [
    { emoji: '✅', slug: '2705' },
    { emoji: '❌', slug: '274c' },
    { emoji: '❓', slug: '2753' },
    { emoji: '❗', slug: '2757' },
    { emoji: '💤', slug: '1f4a4' },
    { emoji: '💢', slug: '1f4a2' },
    { emoji: '♻️', slug: '267b_fe0f' },
    { emoji: '🔔', slug: '1f514' },
    { emoji: '🎵', slug: '1f3b5' },
    { emoji: '⭐', slug: '2b50' },
    { emoji: '🌟', slug: '1f31f' },
    { emoji: '💫', slug: '1f4ab' },
    { emoji: '⚡', slug: '26a1' },
    { emoji: '☀️', slug: '2600_fe0f' },
    { emoji: '🌙', slug: '1f319' },
  ],
}

export const ALL_EMOJI_ENTRIES: EmojiEntry[] = Object.values(EMOJI_CATALOG).flat()

const slugByEmoji = new Map(ALL_EMOJI_ENTRIES.map((entry) => [entry.emoji, entry.slug]))
const entryByEmoji = new Map(ALL_EMOJI_ENTRIES.map((entry) => [entry.emoji, entry]))

export function catalogSlugForEmoji(emoji: string): string | undefined {
  return slugByEmoji.get(emoji)
}

export function catalogEntryForEmoji(emoji: string): EmojiEntry | undefined {
  return entryByEmoji.get(emoji)
}
